```{r Einlesen}
library(igraph)
library(igraphdata)
library(visNetwork)
# library(tcltk)

## Einlesen Edge- und Nodelist
edges <- read.csv("https://raw.githubusercontent.com/DenisUndso/Deutsche-Charts/master/popmusik_el.csv", header=T, as.is=T, sep=",")
nodes <- read.csv("https://raw.githubusercontent.com/DenisUndso/Deutsche-Charts/master/popmusik_nl.csv", header=T, as.is=T, sep=",")
pop <- graph_from_data_frame(d=edges, vertices=nodes, directed=TRUE)
```

```{r Visualisierung}
## Nodeattribute
V(pop)[(V(pop)$type=="2")]$shape <- "square"
V(pop)[(V(pop)$type=="1")]$shape <- "circle"
V(pop)[(V(pop)$type=="2")]$color <- "blue"
V(pop)[(V(pop)$type=="1")]$color <- "red"
V(pop)[(V(pop)$type=="1")]$shape <- "circle"

##Edgeattribute
E(pop)[(E(pop)$type=="1")]$color <- "black"
E(pop)[(E(pop)$type=="2")]$color <- "green"
E(pop)[(E(pop)$type=="3")]$color <- "purple"
```

```{r Erstellen und Auswerten}
## Plotbefehle
visIgraph(pop, type = "full", layout="layout_nicely", smooth=FALSE)
plot(pop, vertex.size=1.5, layout=layout_nicely, edge.arrow.size=.3)
plot(pop, vertex.size=1.5, layout=layout_nicely, edge.arrow.size=.1, vertex.label.dist=1, vertex.label.cex=.5, vertex.label.degree=pi/2)

## Netzwerkparameter
edge_density(pop)
mean_distance(pop)
degree(pop, mode="out")
farthest_vertices(pop)
```


```{r Frauen}
##Nur Frauen Anzeigen
pop_fem <- delete.vertices(pop, V(pop) [sex == "2"])
Isolated = which(degree(pop_fem)==0)
frauen = delete.vertices(pop_fem, Isolated)

visIgraph(frauen, type = "full", layout="layout_nicely", smooth=FALSE)
```

```{r Egograph}
## Erstellen Ego-Graph Vincent Stein
vincent<- make_ego_graph(pop, order=2, c("Vincent Stein"))
plot(vincent[[1]],layout=layout_nicely, edge.arrow.size=0.2)
```

```{r Cluster}
## Cluster anzeigen lassen
pc <- cluster_walktrap(pop)
modularity(pc)
membership(pc)
plot(pc, pop, layout_with_lgl(graph, maxiter = 150, maxdelta = vcount(graph),
  area = vcount(graph)^2, coolexp = 1.5, repulserad = area *
  vcount(graph), cellsize = sqrt(sqrt(area)), root = NULL))
```
Cluster nicht anwendbar, muss entzerrt werden, visIgraph funktioniert nicht
-> evtl. bei Teilnetzwerken sinnvoll
